/*
 * generated by Xtext 2.24.0
 */
package edu.upb.lp.isc;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PipoStandaloneSetup extends PipoStandaloneSetupGenerated {

	public static void doSetup() {
		new PipoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
